parameters:
    btanase_sms.sms_service.class: Btanase\SmsBundle\Service\SmsService

services:
    btanase_sms.dummy_provider:
        class: Btanase\SmsBundle\Service\DummySmsProvider
        arguments:
            apiKey: "%btanase_sms.api_key%"
            postUrl: "%btanase_sms.post_url%"
    btanase_sms.sms_service:
        class: "%btanase_sms.sms_service.class%"
        arguments: ["@btanase_sms.provider"]

